-- Migration 001: Initial Schema
-- SafeReport — HSSE Field Reporting App

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm"; -- for text search on reports

-- ─────────────────────────────────────────────
-- ENUMS
-- ─────────────────────────────────────────────

CREATE TYPE user_role AS ENUM ('end_user', 'approver', 'admin');
CREATE TYPE report_type AS ENUM ('UNSAFE_ACTION', 'UNSAFE_SITUATION', 'SAFE_OBSERVATION');
CREATE TYPE report_status AS ENUM ('draft', 'pending', 'approved', 'rejected');
CREATE TYPE approval_action AS ENUM ('submitted', 'approved', 'rejected', 'resubmitted');

-- ─────────────────────────────────────────────
-- LOCATIONS
-- ─────────────────────────────────────────────

CREATE TABLE locations (
    id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        text NOT NULL,
    code        text,
    parent_id   uuid REFERENCES locations(id) ON DELETE SET NULL,
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_locations_parent ON locations(parent_id);

-- ─────────────────────────────────────────────
-- DEPARTMENTS
-- ─────────────────────────────────────────────

CREATE TABLE departments (
    id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        text NOT NULL,
    parent_id   uuid REFERENCES departments(id) ON DELETE SET NULL,
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_departments_parent ON departments(parent_id);

-- ─────────────────────────────────────────────
-- PROFILES (extends auth.users)
-- ─────────────────────────────────────────────

CREATE TABLE profiles (
    id              uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name       text NOT NULL,
    email           text NOT NULL,
    role            user_role NOT NULL DEFAULT 'end_user',
    department_id   uuid REFERENCES departments(id) ON DELETE SET NULL,
    company         text,
    avatar_url      text,
    is_active       boolean NOT NULL DEFAULT true,
    push_token      text,           -- Expo push token for notifications
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_profiles_role ON profiles(role);
CREATE INDEX idx_profiles_department ON profiles(department_id);

-- ─────────────────────────────────────────────
-- CATEGORIES (master data per report type)
-- ─────────────────────────────────────────────

CREATE TABLE categories (
    id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    report_type report_type NOT NULL,
    name        text NOT NULL,
    parent_id   uuid REFERENCES categories(id) ON DELETE CASCADE,
    sort_order  int NOT NULL DEFAULT 0,
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_categories_report_type ON categories(report_type);
CREATE INDEX idx_categories_parent ON categories(parent_id);

-- ─────────────────────────────────────────────
-- RISK FACTORS (master data)
-- ─────────────────────────────────────────────

CREATE TABLE risk_factors (
    id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    name        text NOT NULL,
    sort_order  int NOT NULL DEFAULT 0,
    is_active   boolean NOT NULL DEFAULT true,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────
-- REPORTS
-- ─────────────────────────────────────────────

CREATE TABLE reports (
    id                      uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    report_number           text UNIQUE,            -- SR-2025-00001, generated by trigger
    report_type             report_type NOT NULL,
    status                  report_status NOT NULL DEFAULT 'draft',

    -- Submitter
    submitted_by            uuid NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,
    on_behalf_of            uuid REFERENCES profiles(id) ON DELETE SET NULL,
    approver_id             uuid REFERENCES profiles(id) ON DELETE SET NULL,

    -- Step 1 — General Info
    location_id             uuid REFERENCES locations(id) ON DELETE SET NULL,
    exact_location          text,
    department_id           uuid REFERENCES departments(id) ON DELETE SET NULL,
    sub_department_id       uuid REFERENCES departments(id) ON DELETE SET NULL,
    company                 text,
    activity                text,
    num_people_observed     int,
    observation_date        timestamptz,

    -- Step 2 — Observation Detail
    observation             text,
    action_taken            text,
    stop_work               boolean NOT NULL DEFAULT false,
    stop_work_category      text,
    stop_work_level         text,
    ptw_number              text,
    further_action_required boolean NOT NULL DEFAULT false,
    hse_concern             boolean NOT NULL DEFAULT false,

    -- Step 3 — Category & Risk
    risk_factor_id          uuid REFERENCES risk_factors(id) ON DELETE SET NULL,
    remarks                 text,

    -- Offline draft
    draft_data              jsonb,

    -- Timestamps
    submitted_at            timestamptz,
    approved_at             timestamptz,
    rejected_at             timestamptz,
    rejection_reason        text,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_reports_submitted_by ON reports(submitted_by);
CREATE INDEX idx_reports_approver ON reports(approver_id);
CREATE INDEX idx_reports_status ON reports(status);
CREATE INDEX idx_reports_report_type ON reports(report_type);
CREATE INDEX idx_reports_observation_date ON reports(observation_date DESC);
CREATE INDEX idx_reports_department ON reports(department_id);

-- ─────────────────────────────────────────────
-- REPORT CATEGORIES (junction)
-- ─────────────────────────────────────────────

CREATE TABLE report_categories (
    report_id   uuid NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    category_id uuid NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (report_id, category_id)
);

-- ─────────────────────────────────────────────
-- REPORT OBSERVERS
-- ─────────────────────────────────────────────

CREATE TABLE report_observers (
    id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    report_id   uuid NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    user_id     uuid REFERENCES profiles(id) ON DELETE SET NULL,
    name        text    -- for non-registered observers
);

CREATE INDEX idx_report_observers_report ON report_observers(report_id);

-- ─────────────────────────────────────────────
-- REPORT ATTACHMENTS
-- ─────────────────────────────────────────────

CREATE TABLE report_attachments (
    id              uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    report_id       uuid NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    storage_path    text NOT NULL,
    file_name       text NOT NULL,
    mime_type       text,
    size_bytes      bigint,
    uploaded_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_report_attachments_report ON report_attachments(report_id);

-- ─────────────────────────────────────────────
-- APPROVAL HISTORY (audit log)
-- ─────────────────────────────────────────────

CREATE TABLE approval_history (
    id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    report_id   uuid NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    action      approval_action NOT NULL,
    actor_id    uuid NOT NULL REFERENCES profiles(id) ON DELETE RESTRICT,
    note        text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_approval_history_report ON approval_history(report_id);
